### PR TITLE
Update pull_request_template.md

### PR DESCRIPTION
**Pull request by lief-erickson**
Add link to coding-guidelines specific to the docs. 

---
name: Pull request
about: Propose changes to fix an issue or implement a new feature

---

## Description
Add link to the documentation coding guidelines

## Motivation and Context
There are links for the Java and XSLT guidelines but not the docs. This PR makes those guidelines also part of the checklist.

### CODE REVIEW

**Review by jelovirt — APPROVED** [review]

**Review by jelovirt — CHANGES_REQUESTED** [review]
The PR should be against develop branch, not master.

**Comment by lief-erickson** [comment]
I'm not seeing a develop branch for this repo. 

Am I missing it? 
https://github.com/dita-ot/.github/branches/all

**Review by infotexture — APPROVED** [review]
Makes sense, thanks. 👍

**Comment by infotexture** [comment]
@jelovirt No `develop` branch, here, only `master`. Merging.

**Pull request merged**
